from __future__ import annotations

from typing import Any, Dict, List, Mapping, Optional, Union

from graphlens_agent.schema import GraphDocument
from graphlens_agent.validator import validate_graph_document


GraphInput = Union[GraphDocument, Mapping[str, Any]]
Narrative = Dict[str, Union[str, List[str]]]


def generate_narrative(graph: GraphInput, analytics: Mapping[str, Any]) -> Narrative:
    """Generate deterministic plain-language narrative sections from graph facts."""

    document = _ensure_document(graph)
    motif = _summary_value(analytics, "graph_motif", "unknown")

    if motif == "fan_in_aggregation":
        return _fan_in_narrative(document, analytics)
    if motif == "fan_out_distribution":
        return _fan_out_narrative(document, analytics)
    return _unknown_narrative(document, analytics)


def _fan_in_narrative(document: GraphDocument, analytics: Mapping[str, Any]) -> Narrative:
    summary = _summary(analytics)
    collector = _collector_label(document, analytics)
    node_count = int(summary.get("node_count", len(document.nodes)))
    edge_count = int(summary.get("edge_count", len(document.edges)))
    collector_behavior = _mapping(analytics.get("collector_behavior"))
    total_inbound_amount = _number_or_none(collector_behavior.get("total_inbound_amount"))

    amount_sentence = ""
    if total_inbound_amount is not None and total_inbound_amount > 0:
        amount_sentence = f" The total inbound amount visible for that node is {_format_amount(total_inbound_amount)}."

    return {
        "Plain-Language Summary": (
            f"This graph shows a fan-in pattern: multiple nodes send edges into {collector}. "
            f"The graph contains {node_count} nodes and {edge_count} edges.{amount_sentence}"
        ),
        "What Is Happening": (
            f"{collector} is acting like a collector node. In plain English, several separate sources point to the "
            "same destination, so the important signal is the shared target rather than any single edge by itself."
        ),
        "Why This Pattern Matters": (
            "Fan-in aggregation can be useful for review because it highlights a destination that receives activity "
            "from multiple sources. This is a review signal, not proof of wrongdoing."
        ),
        "Evidence From the Graph": _evidence_lines(analytics),
        "Suggested Next Review Steps": [
            f"Review the inbound sources connected to {collector}.",
            "Check whether the edge labels or amounts are expected for this graph context.",
            "Compare this structure with neighboring graphs or prior time periods if available.",
            "Confirm labels, directions, and amounts against the original source data before taking action.",
        ],
        "Caveats": _base_caveats(document)
        + [
            "This is a review signal, not proof of wrongdoing.",
            "The narrative is generated by deterministic rules, not by an external model.",
        ],
    }


def _fan_out_narrative(document: GraphDocument, analytics: Mapping[str, Any]) -> Narrative:
    summary = _summary(analytics)
    central_node = _central_node_label(document, analytics)
    node_count = int(summary.get("node_count", len(document.nodes)))
    edge_count = int(summary.get("edge_count", len(document.edges)))

    return {
        "Plain-Language Summary": (
            f"This graph shows a fan-out pattern: {central_node} sends edges to multiple other nodes. "
            f"The graph contains {node_count} nodes and {edge_count} edges."
        ),
        "What Is Happening": (
            f"{central_node} appears to be a distribution point. One source connects outward to several targets."
        ),
        "Why This Pattern Matters": (
            "Fan-out distribution can be useful for review because it highlights one node that may be spreading "
            "activity, information, or value across multiple destinations."
        ),
        "Evidence From the Graph": _evidence_lines(analytics),
        "Suggested Next Review Steps": [
            f"Review the outbound targets connected to {central_node}.",
            "Check whether the repeated outbound structure is expected.",
            "Confirm edge direction and labels against the source data.",
        ],
        "Caveats": _base_caveats(document)
        + [
            "A fan-out pattern can be normal depending on context.",
            "The narrative is generated by deterministic rules, not by an external model.",
        ],
    }


def _unknown_narrative(document: GraphDocument, analytics: Mapping[str, Any]) -> Narrative:
    summary = _summary(analytics)
    node_count = int(summary.get("node_count", len(document.nodes)))
    edge_count = int(summary.get("edge_count", len(document.edges)))

    return {
        "Plain-Language Summary": (
            f"This graph contains {node_count} nodes and {edge_count} edges, but it does not match one of the "
            "currently supported narrative patterns."
        ),
        "What Is Happening": (
            "The graph structure was validated and analyzed, but the rule-based narrative layer does not have a "
            "specific explanation template for this motif."
        ),
        "Why This Pattern Matters": (
            "An unknown motif is still useful for review because it preserves the measured graph facts without "
            "overstating a pattern that the rules did not detect."
        ),
        "Evidence From the Graph": _evidence_lines(analytics),
        "Suggested Next Review Steps": [
            "Inspect the graph visually or compare it with the source system.",
            "Review high-degree nodes and any repeated edge labels or amounts.",
            "Add a new deterministic narrative rule if this pattern is common and meaningful.",
        ],
        "Caveats": _base_caveats(document)
        + [
            "No supported motif-specific narrative was matched.",
            "The narrative is generated by deterministic rules, not by an external model.",
        ],
    }


def _evidence_lines(analytics: Mapping[str, Any]) -> List[str]:
    evidence = analytics.get("evidence", [])
    if isinstance(evidence, list):
        return [str(item) for item in evidence]
    return [str(evidence)]


def _base_caveats(document: GraphDocument) -> List[str]:
    caveats = [
        "Analytics depend on the graph JSON provided to the system.",
        "Use structured source data when available; screenshot extraction is a fallback path.",
    ]
    caveats.extend(document.warnings)
    return caveats


def _collector_label(document: GraphDocument, analytics: Mapping[str, Any]) -> str:
    collector_behavior = _mapping(analytics.get("collector_behavior"))
    collector_id = collector_behavior.get("node_id") or _summary_value(analytics, "collector_node")
    return _node_label(document, collector_id) if collector_id else "the collector node"


def _central_node_label(document: GraphDocument, analytics: Mapping[str, Any]) -> str:
    central_node = _mapping(_summary(analytics).get("central_node"))
    node_id = central_node.get("id")
    return _node_label(document, node_id) if node_id else "the central node"


def _node_label(document: GraphDocument, node_id: Any) -> str:
    for node in document.nodes:
        if node.id == node_id:
            return f"{node.label} ({node.id})"
    return str(node_id)


def _summary(analytics: Mapping[str, Any]) -> Mapping[str, Any]:
    return _mapping(analytics.get("summary"))


def _summary_value(analytics: Mapping[str, Any], key: str, default: Optional[str] = None) -> Optional[str]:
    value = _summary(analytics).get(key, default)
    return str(value) if value is not None else None


def _mapping(value: Any) -> Mapping[str, Any]:
    return value if isinstance(value, Mapping) else {}


def _number_or_none(value: Any) -> Optional[float]:
    if isinstance(value, (int, float)) and not isinstance(value, bool):
        return float(value)
    return None


def _format_amount(value: float) -> str:
    return f"{value:g}"


def _ensure_document(graph: GraphInput) -> GraphDocument:
    if isinstance(graph, GraphDocument):
        return graph
    return validate_graph_document(graph)
